# Generated by Django 4.2.5 on 2023-10-02 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(null=True, verbose_name='amount')),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('creditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='splits_as_creditor', to=settings.AUTH_USER_MODEL, verbose_name='creditor')),
                ('debtor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='splits_as_debtor', to=settings.AUTH_USER_MODEL, verbose_name='debtor')),
            ],
        ),
    ]
