# Generated by Django 4.2.5 on 2023-10-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spliter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='is_closed',
            field=models.BooleanField(default='f'),
        ),
    ]
